packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    '@clack/prompts': ^0.11.0
    axios: ^1.13.4
    bumpp: ^10.3.1
    cac: ^6.7.14
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    mime-types: ^3.0.2
    node-ssh: ^13.2.1
    simple-git-hooks: ^2.13.1
    tinyglobby: ^0.2.15
    tsdown: ^0.16.0
    tsx: ^4.20.6
    typescript: ^5.9.3
    unconfig: ^7.4.2
    vite: ^7.2.1
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.7
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.10.0

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
